### ISSUE TITLE
QUIT_WITHOUT_ENVOY_TIMEOUT	not working

### ISSUE THREAD

**Issue by garyarobinson** [redboxllc/scuttle#40]
I tried setting the environment variable `QUIT_WITHOUT_ENVOY_TIMEOUT` however it appears that it is not being used. This is done in a Docker like the following;

```
ENV QUIT_WITHOUT_ENVOY_TIMEOUT=15s
ENTRYPOINT ["/path/to/scuttle", "..."]
```

 All I get is the following message indefinitely (NB: Envoy is not running)

```
2020-11-10T17:11:40Z scuttle: Scuttle 1.3.1 starting up, pid 1
2020-11-10T17:11:40Z scuttle: Logging is now enabled
2020-11-10T17:11:40Z scuttle: Blocking until Envoy starts
```

**Comment by linjmeyer** [comment]
Fixed in [v1.3.3](https://github.com/redboxllc/scuttle/releases/tag/v1.3.3)
