### ISSUE TITLE
why the package install occurred error

### ISSUE THREAD

**Issue by honghh2018** [redboxllc/scuttle#42]
Hi @All,
     I want to install the package scuttle, but it occurred error like below:
     
![image](https://user-images.githubusercontent.com/41668708/100576087-54362b80-3318-11eb-9522-3eb5d0ae1d29.png)
     What happen to my R ?
      why its head file beachmat3/beachmat.h not found? it make me confused.
      I try anyways that i can do had this question unsolved.
      Any kindly help would be appreciated.
      Best

**Comment by linjmeyer** [comment]
Sorry, I'm not sure what is going wrong :(
