### ISSUE TITLE
Document usage on Alpine

### ISSUE THREAD

**Issue by haf-afa** [redboxllc/scuttle#8]
This line is needed; https://github.com/redboxllc/scuttle/pull/4/files#diff-b8f85395a93f7ac963c933e9d844fd93R10 in the Dockerfile you build of your service; otherwise you an obscure error about "standard-init"

**Comment by linjmeyer** [comment]
Closing as we have since:
* Added simple scuttle image to Docker Hub
* Building with `CGO_ENABLED` to avoid missing runtime dependencies

**Comment by haf-afa** [comment]
Awesome sauce!
